version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=database_test
    
  python:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo
    develop:
      watch:
        - action: rebuild
          path: app
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: Dockerfile
